from model import Model_Aluno
from model import Model_Professor
from model import Model_Materia
from model import Model_Status
from model import Model_Categoria
from model import Model_serie
from model import Model_Carregador
from model import Model_Professor_Materia
from model import Model_Usuario
from model import Model_Emprestimo
from model import Model_Atribuicao_permanente