"""empty message

Revision ID: 0923d504d59f
Revises: 8d90f6a3353b
Create Date: 2025-01-27 10:03:06.704313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0923d504d59f'
down_revision: Union[str, None] = '8d90f6a3353b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta', sa.Column('is_verifed_conta', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta', 'is_verifed_conta')
    # ### end Alembic commands ###
