"""version 1.0 migration

Revision ID: 33ee869eea91
Revises: 
Create Date: 2024-12-17 21:42:49.483645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ee869eea91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome_aluno', sa.String(length=100), nullable=False),
    sa.Column('serie_aluno', sa.Enum('6', '7', '8', '9', name='serie_enum'), nullable=False),
    sa.Column('turma_aluno', sa.Enum('A', 'B', name='turma_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('titulo_categoria', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('materia',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('titulo_materia', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_table('professor',
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('nome_professor', sa.String(length=100), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_professor')
    )
    op.create_table('serie',
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('titulo_serie', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_serie')
    )
    op.create_table('status',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('titulo_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('carregador',
    sa.Column('id_carregador', sa.Integer(), nullable=False),
    sa.Column('matricula_carregador', sa.String(length=5), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_status'], ['status.id_status'], ),
    sa.PrimaryKeyConstraint('id_carregador'),
    sa.UniqueConstraint('matricula_carregador')
    )
    op.create_table('equipamento',
    sa.Column('id_equipamento', sa.Integer(), nullable=False),
    sa.Column('numero_de_serie', sa.String(length=15), nullable=True),
    sa.Column('matricula_equipamento', sa.String(length=5), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_status'], ['status.id_status'], ),
    sa.PrimaryKeyConstraint('id_equipamento')
    )
    op.create_table('professor_materia',
    sa.Column('id_professor_materia', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id_materia'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id_professor'], ),
    sa.PrimaryKeyConstraint('id_professor_materia')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id_professor'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('atribuicao_permanente',
    sa.Column('id_atribuicao_permanente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_equipamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipamento'], ['equipamento.id_equipamento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_atribuicao_permanente')
    )
    op.create_table('emprestimo',
    sa.Column('id_emprestimo', sa.Integer(), nullable=False),
    sa.Column('motivo_emprestimo', sa.String(length=200), nullable=False),
    sa.Column('data_inicio', sa.TIMESTAMP(), nullable=False),
    sa.Column('data_fim', sa.TIMESTAMP(), nullable=False),
    sa.Column('id_equipamento', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_equipamento'], ['equipamento.id_equipamento'], ),
    sa.PrimaryKeyConstraint('id_emprestimo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimo')
    op.drop_table('atribuicao_permanente')
    op.drop_table('usuario')
    op.drop_table('professor_materia')
    op.drop_table('equipamento')
    op.drop_table('carregador')
    op.drop_table('status')
    op.drop_table('serie')
    op.drop_table('professor')
    op.drop_table('materia')
    op.drop_table('categoria')
    op.drop_table('aluno')
    # ### end Alembic commands ###
