"""empty message

Revision ID: 8ca30250ec76
Revises: 
Create Date: 2025-01-12 18:11:41.108592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca30250ec76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serie',
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('titulo_serie', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_serie')
    )
    op.alter_column('aluno', 'serie_aluno',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('6', '7', '8', '9', name='serie_enum'),
               existing_nullable=False)
    op.alter_column('aluno', 'turma_aluno',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Enum('A', 'B', name='turma_enum'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'carregador', ['matricula_carregador'])
    op.add_column('emprestimo', sa.Column('data_inicio', sa.TIMESTAMP(), nullable=False))
    op.add_column('emprestimo', sa.Column('data_fim', sa.TIMESTAMP(), nullable=False))
    op.add_column('emprestimo', sa.Column('nome_usuario', sa.String(length=100), nullable=False))
    op.drop_constraint('emprestimo_id_usuario_fkey', 'emprestimo', type_='foreignkey')
    op.drop_column('emprestimo', 'data_inicio_emprestimo')
    op.drop_column('emprestimo', 'data_fim_emprestimo')
    op.drop_column('emprestimo', 'id_usuario')
    op.add_column('equipamento', sa.Column('numero_de_serie', sa.String(length=15), nullable=True))
    op.drop_constraint('equipamento_id_carregador_fkey', 'equipamento', type_='foreignkey')
    op.drop_column('equipamento', 'numero_de_serie_equipamento')
    op.drop_column('equipamento', 'id_carregador')
    op.add_column('professor', sa.Column('id_materia', sa.Integer(), nullable=False))
    op.alter_column('usuario', 'id_aluno',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario', 'id_professor',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'id_professor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuario', 'id_aluno',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('professor', 'id_materia')
    op.add_column('equipamento', sa.Column('id_carregador', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('equipamento', sa.Column('numero_de_serie_equipamento', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.create_foreign_key('equipamento_id_carregador_fkey', 'equipamento', 'carregador', ['id_carregador'], ['id_carregador'])
    op.drop_column('equipamento', 'numero_de_serie')
    op.add_column('emprestimo', sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('emprestimo', sa.Column('data_fim_emprestimo', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('emprestimo', sa.Column('data_inicio_emprestimo', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key('emprestimo_id_usuario_fkey', 'emprestimo', 'usuario', ['id_usuario'], ['id_usuario'])
    op.drop_column('emprestimo', 'nome_usuario')
    op.drop_column('emprestimo', 'data_fim')
    op.drop_column('emprestimo', 'data_inicio')
    op.drop_constraint(None, 'carregador', type_='unique')
    op.alter_column('aluno', 'turma_aluno',
               existing_type=sa.Enum('A', 'B', name='turma_enum'),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    op.alter_column('aluno', 'serie_aluno',
               existing_type=sa.Enum('6', '7', '8', '9', name='serie_enum'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('serie')
    # ### end Alembic commands ###
