"""empty message

Revision ID: f3d3be9f6944
Revises: 
Create Date: 2025-01-30 21:31:28.464449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d3be9f6944'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('conta', sa.Column('is_verifed_conta', sa.Boolean(), nullable=True))

    # Define um valor padrão para registros existentes
    op.execute("UPDATE conta SET is_verifed_conta = FALSE")

    # Agora, altera para NOT NULL
    op.alter_column('conta', 'is_verifed_conta', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta', 'is_verifed_conta')
    # ### end Alembic commands ###
